# Generated by Django 5.0.7 on 2024-07-22 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пациент",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.doctors",
                verbose_name="врач",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="doctor",
            field=models.ManyToManyField(to="main.doctors", verbose_name="врач"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.services",
                verbose_name="выбранная услуга",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.specializations",
                verbose_name="специализация",
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="specialty",
            field=models.ManyToManyField(
                to="main.specializations", verbose_name="специализация"
            ),
        ),
    ]
