# Generated by Django 4.2.2 on 2024-07-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_appointment_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.services",
                verbose_name="выбранная услуга",
            ),
        ),
    ]
