# Generated by Django 4.2.2 on 2024-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_appointment_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="specialty",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="main.specializations",
                verbose_name="специализация",
            ),
        ),
    ]
