# Generated by Django 4.2.2 on 2024-08-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_doctors_specialty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctors",
            name="specialty",
        ),
        migrations.AddField(
            model_name="doctors",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.specializations",
                verbose_name="специализация",
            ),
        ),
    ]
