# Generated by Django 4.2.2 on 2024-08-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_doctors_specialty_doctors_specialty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.specializations",
                verbose_name="специализация",
            ),
        ),
    ]
